AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Monitoring Amazon S3 Backups with CloudWatch Dashboards and Alarms

Parameters:
  MyBucket:
    Description: Amazon S3 Bucket to store backup data. This name MUST be globally unique. Please see naming rules https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
    Type: String
    MinLength: 1
  MyEmailAddress:
    Description: SNS Subscription Email address to receive notifications of failed backups to S3
    Type: String
    MinLength: 1
    
Globals: 
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11
    Architectures:
      - arm64 #Lambda function will run on Arm-based AWS Graviton processors

Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${MyBucket}"
    
  CustomMetricsFunction:
    Type: AWS::Serverless::Function    
    Properties:
      Handler: app.lambda_handler
      CodeUri: monitor
      Layers:
      - arn:aws:lambda:af-south-1:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:45
      Events:
        BackupEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: BackupBucket
            Events: s3:ObjectCreated:*
      Environment:
        Variables:
          POWERTOOLS_METRICS_NAMESPACE: BackupsMonitoring
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "${MyBucket}"

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Sub "${MyEmailAddress}"
          Protocol: "email"

  CloudWatchDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties: 
      DashboardName: BackupsMonitoring #TODO: Paramatrise region and period
      DashboardBody: | #The | (pipe) indicates that everything below is a string literal
                  {
                      "periodOverride": "inherit",
                      "widgets": [
                          {
                            "type":"metric",
                            "x":0,
                            "y":0,
                            "width":12,
                            "height":10,
                            "properties":{
                                "metrics":[
                                  [ { "expression": "FILL(SEARCH(' {BackupsMonitoring, System} MetricName=\"Backups\" ', 'Sum'), 0)", "id": "e1" } ]
                                  ],
                                "period":3600,
                                "stat":"Sum",
                                "region":"af-south-1",
                                "title":"Backups to S3",
                                "liveData": false,
                                "legend": {
                                    "position": "right"
                                  }
                            }
                          }
                      ]
                    }