AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Monitoring Amazon S3 Backups with CloudWatch Dashboards and Alarms

Parameters:
  MyBucket:
    Description: Amazon S3 Bucket to store backup data. Must not be an existing bucket, and the name must be globally unique. Please see S3 Bucket naming rules https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
    Type: String
    MinLength: 1
  MyEmailAddress:
    Description: SNS Subscription Email address to receive notifications from CloudWatch alarms of failed backups to S3. Must be a valid email address.
    Type: String
    MinLength: 5
  MetricName:
    Description: The name of the CloudWatch metric that should be used. Can be any string. The default is "Backups"
    Type: String
    MinLength: 1
    Default: "Backups"
  DimensionName:
    Description: The name of the CloudWatch dimension that should be used for the above metric, based on what each S3 folder represents. E.g each folder can represent a System, Location or Customer, that you doing backups for. Can be any string. The default is "System"
    Type: String
    MinLength: 1
    Default: "System"
  BackupFrequencyPeriod:
    Description: What schedule/frequency does your backups run, e.g. Hourly, daily, weekly? The value must be represented in seconds. The default is 86400 seconds = 1 day, i.e. you expect that files are backed up to S3 daily.
    Type: Number
    MinValue: 1
    ConstraintDescription: "Must be in seconds"
    Default: 86400
    
Globals: 
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.11
    CodeUri: monitor
    Architectures:
      - arm64 #Lambda function will run on Arm-based AWS Graviton processors. The Powertools Lamba layer will also be Arm based
    Environment:
        Variables:
          POWERTOOLS_METRICS_NAMESPACE: BackupsMonitoring
          #POWERTOOLS_SERVICE_NAME: S3Backups #TODO see if this fixes the CloudWatch Math Search, but misses Logging info
          LOG_LEVEL: INFO
          SNSTopic: !Ref EmailNotificationsSNSTopic
          MetricName: !Ref MetricName
          DimensionName: !Ref DimensionName
          BackupFrequencyPeriod: !Ref BackupFrequencyPeriod  

Resources:
  BackupBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub "${MyBucket}"
    
  CustomMetricsFunction:
    Type: AWS::Serverless::Function    
    Properties:
      Handler: metrics.lambda_handler
      Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:45
      Events:
        BackupEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: BackupBucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "${MyBucket}"

  AlarmsFunction:
    Type: AWS::Serverless::Function    
    Properties:
      Handler: alarms.lambda_handler
      Layers:
      - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV2-Arm64:45
      Policies:
        - Statement:
          - Effect: "Allow"
            Action:
              - cloudwatch:PutMetricAlarm 
              - cloudwatch:ListMetrics
            Resource:
              - '*'
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 * * * ? *) #run every hour, on the hour (at the 0th minute)

  EmailNotificationsSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Sub "${MyEmailAddress}"
          Protocol: "email"

  CloudWatchDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties: 
      DashboardName: BackupsMonitoring #TODO: Paramatrise  period 
      DashboardBody: !Sub "  
                  {
                      \"periodOverride\": \"inherit\",
                      \"widgets\": [
                          {
                            \"type\":\"metric\",
                            \"x\":0,
                            \"y\":0,
                            \"width\":12,
                            \"height\":10,
                            \"properties\":{
                                \"metrics\":[
                                  [ { \"expression\": \"FILL(SEARCH(' {BackupsMonitoring, ${DimensionName}} MetricName=\\\"${MetricName}\\\" ', 'Sum'), 0)\", \"id\": \"e1\" } ]
                                  ],
                                \"period\":${BackupFrequencyPeriod},
                                \"region\":\"${AWS::Region}\",
                                \"title\":\"Backups to S3\",
                                \"legend\": {
                                    \"position\": \"right\"
                                  }
                            }
                          }
                      ]
                    }    
                    "     